# Generated by Django 4.2.11 on 2024-05-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='province',
        ),
        migrations.RemoveField(
            model_name='property',
            name='state',
        ),
        migrations.AddField(
            model_name='property',
            name='longLat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.CharField(max_length=200),
        ),
    ]
