# Generated by Django 4.2.11 on 2024-05-21 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_property_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitation',
            old_name='for_admin',
            new_name='is_used',
        ),
    ]
