# Generated by Django 4.2.11 on 2024-05-08 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_customuser_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.BooleanField(default=False)),
                ('seller', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('token_sent', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('offered_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('comments', models.CharField(blank=True, max_length=200, null=True)),
                ('offer_state', models.CharField(choices=[('aceptada', 'Oferta aceptada'), ('rechazada', 'Oferta rechazada'), ('pendiente', 'Oferta pendiente'), ('cancelada', 'Oferta cancelada')], default='pendiente', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reservation_date', models.DateTimeField()),
                ('comments', models.CharField(blank=True, max_length=200, null=True)),
                ('reservation_state', models.CharField(choices=[('reservada', 'Reserva realizada'), ('no_reservada', 'Reserva no realizada'), ('pendiente', 'Reserva pendiente'), ('cancelada', 'Reserva cancelada')], default='pendiente', max_length=100)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='api.offer')),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='email_verified',
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('comments', models.CharField(blank=True, max_length=200, null=True)),
                ('visit_state', models.CharField(choices=[('realizada', 'Visita realizada'), ('no_realizada', 'Visita no realizada'), ('pendiente', 'Visita pendiente'), ('cancelada', 'Visita cancelada')], default='pendiente', max_length=100)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='api.client')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='api.property')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sale_date', models.DateTimeField()),
                ('comments', models.CharField(blank=True, max_length=200, null=True)),
                ('sale_state', models.CharField(choices=[('vendida', 'Venta realizada'), ('no_vendida', 'Venta no realizada'), ('pendiente', 'Venta pendiente'), ('cancelada', 'Venta cancelada')], default='pendiente', max_length=100)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='api.reservation')),
            ],
        ),
        migrations.AddField(
            model_name='offer',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offer',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='api.client'),
        ),
        migrations.AddField(
            model_name='offer',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='api.property'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.client')),
            ],
        ),
    ]
