# Generated by Django 4.2.11 on 2024-05-21 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_for_admin_invitation_is_used'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitation',
            old_name='token_sent',
            new_name='token',
        ),
    ]
