# Generated by Django 4.2.11 on 2024-05-21 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_token_sent_invitation_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyimage',
            old_name='product',
            new_name='property',
        ),
    ]
